Fixed test-issue when tests did not submit a proper Run object.
This does not yet fix the issue with other tests failing with messages
like these:

"scm polling should not detect any more changes after build"
"The build should have only one culprit expected:<1> but was:<0>"
"commitFile1 file not found in workspace"

These will be fixed as soon as I have identified the root-cause of them.