[JENKINS-45504] Add discovery symbol to branch and tag trait
When configuring multibranch pipelines without blueocean installed, the
Git SCM source for branch discovery and tag discovery works fine.
However, when installing blue ocean it includes dependencies which cause
a conflict in the DSL.  The conflicting plugins are:

- cloudbees-bitbucket-branch-source
- github-branch-source

The exception experienced when using Job DSL to call on the branch
discovery trait or tag discovery trait is the following.

```
ERROR: Found multiple extensions which provide method branchDiscoveryTrait with arguments []: [[com.cloudbees.jenkins.plugins.bitbucket.BranchDiscoveryTrait, jenkins.plugins.git.traits.BranchDiscoveryTrait, org.jenkinsci.plugins.github_branch_source.BranchDiscoveryTrait]]
```

See also:

- [JENKINS-45504][JENKINS-45504] Add `@Symbol` annotations to traits
- [JENKINS-45688][JENKINS-45688] Unable to set extensions for Git SCM
  Source via DSL

**Tested**

Installed the development snapshot of this change into Jenkins 2.107.3
which required also compiling [git-client-plugin][git-client] from master
branch source.

[JENKINS-45688]: https://issues.jenkins-ci.org/browse/JENKINS-45688
[JENKINS-45504]: https://issues.jenkins-ci.org/browse/JENKINS-45504
[git-client]: https://github.com/jenkinsci/git-client-plugin