Do not report the same error message twice.
Message passed to AbortException gets printed, so it results in the same message printed twice:

Cloning the remote Git repository
Cloning repository http://example.com/scm/demo/maven-demo.git
 > git init /path/blah/foo/workspace # timeout=10
Fetching upstream changes from http://example.com/scm/demo/maven-demo.git
 > git --version # timeout=10
ERROR: Error cloning remote repo 'origin'
ERROR: Error cloning remote repo 'origin'
Finished: FAILURE